"""Init

Revision ID: 2601b618fe41
Revises: 
Create Date: 2024-04-06 19:28:41.509123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.services.auth import auth_service


# revision identifiers, used by Alembic.
revision: str = '2601b618fe41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='userrole'), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    created_at = sa.func.now()
    op.bulk_insert(
        users,
        [
            {
                # "id": 1,
                "username": "admin",
                "email": "admin@email.com",
                "password": auth_service.get_password_hash("admin"),
                "created_at": created_at,
                # "avatar": "",
                "confirmed": True,
                "roles": "admin",
                "is_banned": False,
            },
        ],
        multiinsert=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute("drop type userrole")
    # ### end Alembic commands ###
