"""Init

Revision ID: 850aa22b160f
Revises: 
Create Date: 2023-10-10 21:56:20.865276

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa

from src.services.auth import auth_service

# revision identifiers, used by Alembic.
revision: str = '850aa22b160f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('crated_at', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    op.bulk_insert(
        users,
        [
            {
                "id": 1,
                "username": "admin",
                "email": "admin@email.com",
                "crated_at": datetime.now(),
                "password": auth_service.get_password_hash("admin"),
                "confirmed": True,
                "roles": "admin",
            },
        ],
        multiinsert=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute("drop type role")
    # ### end Alembic commands ###
